// @ts-nocheck -- skip type checking
import * as docs_6 from "../content/docs/eight-part-essay/react/1.mdx?collection=docs&hash=1760079762877"
import * as docs_5 from "../content/docs/eight-part-essay/html/1.mdx?collection=docs&hash=1760079762877"
import * as docs_4 from "../content/docs/eight-part-essay/js/2.mdx?collection=docs&hash=1760079762877"
import * as docs_3 from "../content/docs/eight-part-essay/css/1.mdx?collection=docs&hash=1760079762877"
import * as docs_2 from "../content/docs/study-note/1.mdx?collection=docs&hash=1760079762877"
import * as docs_1 from "../content/docs/some-think/1.mdx?collection=docs&hash=1760079762877"
import * as docs_0 from "../content/docs/eight-part-essay/1.mdx?collection=docs&hash=1760079762877"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"eight-part-essay\\1.mdx","absolutePath":"D:/code/web/fumadco/my/content/docs/eight-part-essay/1.mdx"}, data: docs_0 }, { info: {"path":"some-think\\1.mdx","absolutePath":"D:/code/web/fumadco/my/content/docs/some-think/1.mdx"}, data: docs_1 }, { info: {"path":"study-note\\1.mdx","absolutePath":"D:/code/web/fumadco/my/content/docs/study-note/1.mdx"}, data: docs_2 }, { info: {"path":"eight-part-essay\\css\\1.mdx","absolutePath":"D:/code/web/fumadco/my/content/docs/eight-part-essay/css/1.mdx"}, data: docs_3 }, { info: {"path":"eight-part-essay\\js\\2.mdx","absolutePath":"D:/code/web/fumadco/my/content/docs/eight-part-essay/js/2.mdx"}, data: docs_4 }, { info: {"path":"eight-part-essay\\html\\1.mdx","absolutePath":"D:/code/web/fumadco/my/content/docs/eight-part-essay/html/1.mdx"}, data: docs_5 }, { info: {"path":"eight-part-essay\\react\\1.mdx","absolutePath":"D:/code/web/fumadco/my/content/docs/eight-part-essay/react/1.mdx"}, data: docs_6 }], [{"info":{"path":"meta.json","absolutePath":"D:/code/web/fumadco/my/content/docs/meta.json"},"data":{"title":"学习笔记","pages":["eight-part-essay","some-think","study-note"],"description":"学习笔记"}}, {"info":{"path":"eight-part-essay\\meta.json","absolutePath":"D:/code/web/fumadco/my/content/docs/eight-part-essay/meta.json"},"data":{"title":"八股文","pages":["js","react","css","html","tailwind"],"description":"八股文","root":true}}, {"info":{"path":"study-note\\meta.json","absolutePath":"D:/code/web/fumadco/my/content/docs/study-note/meta.json"},"data":{"title":"学习笔记","pages":["1"],"description":"学习笔记","root":true}}, {"info":{"path":"some-think\\meta.json","absolutePath":"D:/code/web/fumadco/my/content/docs/some-think/meta.json"},"data":{"title":"一些思考","description":"一些思考","root":true}}, {"info":{"path":"eight-part-essay\\js\\meta.json","absolutePath":"D:/code/web/fumadco/my/content/docs/eight-part-essay/js/meta.json"},"data":{"title":"JS","pages":["2"],"description":"JS","defaultOpen":true}}])